version: '3.8'
services:
  backend:
    env_file:
      - backend/src/.env
    build:
      context: ./backend
      dockerfile: ./docker/go/Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  db:
    build: 
      context: ./backend 
      dockerfile: ./docker/db/Dockerfile.dev
    env_file:
      - ./backend/src/.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    volumes:
      - ./src/database/initdb.d:/docker-init-entrypoint.d