version: '3.8'
services:
  backend:
    env_file:
      - backend/.env
    build:
      context: ./backend
      dockerfile: ./docker/go/Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  db:
    image: mysql:8.0
    environment:
      - DB_ROOT_PASSWORD
      - DB_DATABASE
      - DB_USER
      - DB_PASSWORD
    restart: always
    volumes:
      - ./database/initdb.d:/docker-init-entrypoint.d